---
title: "Module1_NewcustomerList"
author: "Thomas Nguyen"
date: "14/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r include = FALSE}
library(tidyverse)
library(readxl)
library(fpp3)
library(openxlsx)
library(naniar)
library(kableExtra)
library(eeptools)
library(tidymodels)
library(randomForest)

```
## Prepare transaction dataset
```{r}
KPMG_trans <- read_xlsx(here::here("data/KPMG_VI_New_raw_data_update_final.xlsx"), sheet = "Transactions", skip = 1) 
KPMG_trans %>% miss_var_summary()
KPMG_trans_cus_saleprice<-  KPMG_trans %>% 
  select(transaction_id, customer_id, list_price, standard_cost) %>%
  group_by(customer_id) %>% 
  summarise(sale_price = sum(list_price))
```

## Prepare customer dataset
```{r}
KPMG_cus <- read_xlsx(here::here("data/KPMG_VI_New_raw_data_update_final.xlsx"), sheet = "CustomerDemographic", skip = 1) %>%
  mutate(DOB = convertToDate(DOB)) %>%
  select(-default) 

# calculate age from dob
KPMG_cus <- KPMG_cus %>% drop_na(DOB) %>%
  mutate(age = round(age_calc(DOB, enddate = Sys.Date(), units = "years"),0)) %>%
  mutate(gender = if_else(tolower(gender) %in% c("f", "femal"), "Female", gender)) %>%
  mutate(gender = if_else(tolower(gender) == "m", "Male", gender))  %>%
  rename( "p3year_purchases" = "past_3_years_bike_related_purchases", 
          "job_cat" = "job_industry_category") %>% 
  select(-DOB)
```





```{r}
KPMG_newcus <- read_xlsx(here::here("data/KPMG_VI_New_raw_data_update_final.xlsx"), sheet = "NewCustomerList", skip = 1) %>%
  mutate(id = row_number())
KPMG_newcus_datefix1 <- KPMG_newcus %>% 
  mutate(dob = ymd(DOB)) %>% drop_na(dob)
KPMG_newcus_datefix2 <-  KPMG_newcus %>%  mutate(dob = convertToDate(DOB)) %>% drop_na(dob)

KPMG_newcus_datefix <- rbind(KPMG_newcus_datefix1, KPMG_newcus_datefix2)


KPMG_newcus <- KPMG_newcus_datefix %>% 
  mutate(age = round(age_calc(dob, enddate = Sys.Date(), units = "years"),0))


KPMG_newcus_test <- KPMG_newcus %>% select(id, gender, age, past_3_years_bike_related_purchases, dob, job_industry_category, wealth_segment, deceased_indicator, owns_car, tenure, postcode, state, property_valuation) %>%
  rename( "p3year_purchases" = "past_3_years_bike_related_purchases")
```

## Prepare customer dataset

```{r}
KPMG_address <- read_xlsx(here::here("data/KPMG_VI_New_raw_data_update_final.xlsx"), sheet = "CustomerAddress", skip = 1) %>%
  mutate(state = if_else(tolower(state) == "new south wales", "NSW", state)) %>%
  mutate(state = if_else(tolower(state) == "victoria", "VIC", state)) %>%
  select(-c(address, country))


unique(KPMG_address$state)

```

## Joining dataset, prepare for learning
```{r}
# join customer demographic and customer address. There are 4 customer without postcode + state + property valuation (0.1%, acceptable))


# Join with transaction. Note that saleprices has a lot of missing values 
KPMG_cus_info_final <- KPMG_cus %>% left_join(KPMG_address, by = "customer_id") %>% left_join(KPMG_trans_cus_saleprice, by = "customer_id") 
KPMG_cus_info_final %>% miss_var_summary()

```


```{r}

# Right skewed data => sqrt to make it more normal

KPMG_cus_info_final %>% ggplot(aes(x = sqrt(sale_price)))+ geom_histogram()
KPMG_cus_info_final %>% filter(age <70) %>% ggplot(aes(x = age))+ geom_histogram()

```



### Deal with post code
```{r}
# Things that needed to report here: Change some variables to factor, dealed with postcode, calculate total sale price per customer and squareroot it, some outliers in age variable

australian_postcodes <- read_csv(here::here("data/australian_postcodes.csv")) %>% select(postcode, long,lat) %>%
  mutate(postcode = as.numeric(postcode)) %>%
  group_by(postcode) %>%
  summarize(long = mean(long),
            lat = mean(lat))

# How to deal with zip code: https://stats.stackexchange.com/questions/94902/how-to-represent-geography-or-zip-code-in-machine-learning-model-or-recommender


KPMG_cus_info_tr<-  recipe(~ customer_id + p3year_purchases+ 
                             gender + job_cat+  wealth_segment+ 
                             deceased_indicator+ owns_car+
                             tenure+ age+ postcode + state + property_valuation+ sale_price, data = KPMG_cus_info_final) %>%
  step_sqrt(sale_price) %>%
  step_string2factor(gender, job_cat, wealth_segment, deceased_indicator, owns_car, state) %>%
  prep(training = KPMG_cus_info_final,
       strings_as_factors = FALSE) %>%
  bake(new_data = NULL)


KPMG_cus_info_tr <- KPMG_cus_info_tr %>% left_join(australian_postcodes, by = "postcode") %>% filter(age < 70)


```

```{r}
binner <- function(x) {
  x <- cut(x, breaks = 35 * c(0, 1, 2, 3), include.lowest = TRUE)
  # now return the group number
  as.numeric(x)
}

inc <- c("low", "med", "high")
rec <-
  recipe(customer_id ~ sale_price, data = KPMG_cus_info_tr) %>%
  step_num2factor(
    sale_price,
    transform = binner,
    levels = inc,
    ordered = TRUE
  ) %>%
  prep()
rec %>% bake(new_data = NULL)
```

```{r}

KPMG_cus_info_tr <-   recipe(~ customer_id + p3year_purchases+ 
                             gender + job_cat+  wealth_segment+ 
                             deceased_indicator+ owns_car+
                             tenure+ age+ postcode + state + property_valuation+ sale_price + long + lat, data = KPMG_cus_info_tr) %>%
  step_num2factor(
    sale_price,
    transform = binner,
    levels = inc,
    ordered = TRUE
  ) %>%
  prep() %>%
  bake(new_data = NULL)


saveRDS(KPMG_cus_info_tr, file = here::here("data/KPMG_cus_info_tr"))
```


### Build the model


```{r}
set.seed(2307)
split <- initial_split(KPMG_cus_info_tr, 3/4, strata = "sale_price")
KPMG_tr <- training(split)
KPMG_ts <- testing(split)

```


```{r}
set.seed(3000)
# Fit a basic model
KPMG_rf <- rand_forest() %>%
  set_engine("randomForest",
             importance=TRUE, proximity=TRUE) %>%
  set_mode("regression") %>%
  fit(sale_price~., data=KPMG_tr)

KPMG_rf$fit$importance

```

```{r}
KPMG_rf2 <- rand_forest() %>%
  set_engine("randomForest",
             importance=TRUE, proximity=TRUE) %>%
  set_mode("classification") %>%
  fit(sale_price~p3year_purchases + gender + job_cat + wealth_segment+ owns_car + tenure + age+ state + property_valuation + long + lat, data=KPMG_tr)

KPMG_rf2$fit$importance

```
```{r}

```

